# Generated by Django 4.0.5 on 2022-08-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMBIGUEDADES', '0002_alter_fileupload_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, max_length=5000)),
                ('classification', models.TextField(blank=True, max_length=5000)),
                ('status', models.TextField(blank=True, max_length=5000)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
