# Generated by Django 4.0.5 on 2022-09-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMBIGUEDADES', '0004_remove_file_classification_remove_file_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiguedad',
            name='requisito',
            field=models.TextField(default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='ambiguedad',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ambiguedad',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
