# Generated by Django 4.0.5 on 2022-09-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMBIGUEDADES', '0005_ambiguedad_requisito_alter_ambiguedad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiguedad',
            name='requisito',
            field=models.CharField(default='', max_length=800),
        ),
    ]
