# Generated by Django 4.0.5 on 2022-09-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMBIGUEDADES', '0006_alter_ambiguedad_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiguedad',
            name='requisito',
            field=models.CharField(default='', max_length=255),
        ),
    ]
